stages:
  - unit
  - e2e

unit-test:
    image: openjdk:12
    script: ./gradlew test
    stage: unit
    artifacts:
        reports:
            junit: build/test-results/test/TEST-*.xml

e2e-test:
  image: registry.gitlab.com/finestructure/pipeline-trigger
  stage: e2e
  script:
    - echo "API TOKEN = $API_TOKEN , CI JOB TOKEN = $CI_JOB_TOKEN , JALIEN REPO = $CI_REPOSITORY_URL , JALIEN BRANCH = $CI_COMMIT_REF_NAME"
    - trigger -h gitlab.cern.ch -a "$API_TOKEN" -p "$CI_JOB_TOKEN" -t dev -e JALIEN_REPO=$CI_REPOSITORY_URL -e JALIEN_BRANCH=$CI_COMMIT_REF_NAME 46440

