stages:
  - unit
  - e2e

unit-test:
    image: openjdk:12
    script: ./gradlew test
    stage: unit
    artifacts:
        reports:
            junit: build/test-results/test/TEST-*.xml

e2e-test:
  image: registry.gitlab.com/finestructure/pipeline-trigger
  stage: e2e
  variables: 
    CI_DEBUG_TRACE: "true"
  script:
    - export
    - echo "API TOKEN = $API_TOKEN , CI JOB TOKEN = $CI_JOB_TOKEN , JALIEN REPO = $CI_REPOSITORY_URL , JALIEN BRANCH = $CI_COMMIT_REF_NAME"
    - curl -X POST -F token=429b27d63b3bd0b2734079cf78d31f -F ref=$CI_COMMIT_REF_NAME https://gitlab.cern.ch/api/v4/projects/50/trigger/pipeline
